# Generated by Django 5.0.2 on 2024-03-06 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sneaksbid', '0004_rename_description_long_item_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(default='PS D:\\Project-ase\\sneaksbid-app> python manage.py makemigrations', upload_to=''),
            preserve_default=False,
        ),
    ]
