# Generated by Django 5.0.2 on 2024-03-06 18:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sneaksbid', '0005_item_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='bid_expiry',
            new_name='post_time',
        ),
        migrations.RemoveField(
            model_name='item',
            name='current_bid',
        ),
        migrations.AddField(
            model_name='item',
            name='auction_duration',
            field=models.DurationField(default=datetime.timedelta(seconds=300)),
        ),
        migrations.AddField(
            model_name='item',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
