# Generated by Django 5.0.3 on 2024-03-16 19:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sneaksbid', '0007_order_billingaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='auction_duration',
            field=models.DurationField(default=datetime.timedelta(days=1)),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(upload_to='items/'),
        ),
    ]
