# Generated by Django 5.0.3 on 2024-03-17 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sneaksbid', '0009_alter_item_auction_duration_alter_item_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shoe',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sneaksbid.item')),
                ('size', models.CharField(max_length=10)),
            ],
            bases=('sneaksbid.item',),
        ),
    ]
