# Generated by Django 5.0.3 on 2024-03-19 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sneaksbid', '0012_bid_is_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingaddress',
            name='payment_option',
            field=models.CharField(default='S', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='billingaddress',
            name='same_shipping_address',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='billingaddress',
            name='save_info',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='billingaddress',
            name='apartment_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
