# Generated by Django 5.0.3 on 2024-03-21 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sneaksbid', '0016_cart_cartitem_cart_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='item',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
